name = "feedi-brine-dev"
main = "worker/index.js"
compatibility_date = "2025-01-01"

[assets]
directory = "."
not_found_handling = "single-page-application"
binding = "ASSETS"

[[kv_namespaces]]
binding = "KV"
id = "31af68a490ad48a2a5a92248ca0cf957"

[[durable_objects.bindings]]
name = "ANALYTICS"
class_name = "AnalyticsDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["AnalyticsDO"]

[[r2_buckets]]
binding = "R2"
bucket_name = "feedi-brine-dev"

[triggers]
crons = ["0 2 * * *"]
