name = "feedi-brine-dev"
main = "worker/index.js"
compatibility_date = "2025-01-01"

[assets]
directory = "assets"
not_found_handling = "single-page-application"
binding = "ASSETS"
run_worker_first = true

[vars]
DOMAIN_NAME = "feedi.brine.dev"
OWNER = "AMOCqVCs9-TMcPsayX9cF7l1veoEPgbzEIZRlPw_zp8"  # paste your pubkey here after deriving it at /admin

[[kv_namespaces]]
binding = "FEEDI_KV"
id = "5ba3319ac1304f2fabc391fcbbae65ca"

[[durable_objects.bindings]]
name = "ANALYTICS"
class_name = "AnalyticsDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["AnalyticsDO"]

[[r2_buckets]]
binding = "R2"
bucket_name = "feedi-brine-dev"

[triggers]
crons = ["0 * * * *"]

[observability]
enabled = true

[observability.logs]
enabled = true

# DEV

[env.dev]
name = "feedi3"

[env.dev.vars]
DOMAIN_NAME = "feedi.brine.dev"
OWNER = "14QvqWeWgoQu5AB5dqrUpqmasLH92Pp9kgbL3puL2DU"  # paste your pubkey here after deriving it at /admin

[[env.dev.kv_namespaces]]
binding = "FEEDI_KV"
id = "5ba3319ac1304f2fabc391fcbbae65ca"

[[env.dev.durable_objects.bindings]]
name = "ANALYTICS"
class_name = "AnalyticsDO"

[[env.dev.migrations]]
tag = "v1"
new_sqlite_classes = ["AnalyticsDO"]

[[env.dev.r2_buckets]]
binding = "R2"
bucket_name = "feedi-brine-dev"
